### ISSUE TITLE
你好，咨询一下

### ISSUE THREAD

**Issue by YAANNZ** [devcxm/iOS-Images-Extractor#1]
我扒了一下轻单的图片，还是有很多找不见，不知道.car文件还有没有别的方式打开？

**Comment by YAANNZ** [comment]
我用ThemeEngine打开了，只是导出的图片都没了名字

**Comment by devcxm** [comment]
本来我就想让你试试[ThemeEngine](https://github.com/alexzielenski/ThemeEngine)和[cartool](https://github.com/steventroughtonsmith/cartool)

问一下，你使用的系统版本是多少？

**Comment by YAANNZ** [comment]
嗯，我电脑10.10，我在[这里](http://joaoa.com/ThemeEngine/)<br />下载的ThemeEngine。cartool看了看不会用，，

**Comment by devcxm** [comment]
更新了CARExtractor
