### ISSUE TITLE
Can't extract things out from Assets.car of ofo 1.80 

### ISSUE THREAD

**Issue by mayongl** [devcxm/iOS-Images-Extractor#10]
iOSImagesExtractor_v0.3.1

The program ends immediately after clicking start. And the CarFilesOutput folder is empty.

The assets.car is attached. Just remove the .zip extension from file name. 

Thanks & Regards

[Assets.car.zip](https://github.com/devcxm/iOS-Images-Extractor/files/632625/Assets.car.zip)

**Comment by mayongl** [comment]
Assertion failed: (tokenCount < maxCountIncludingZeroTerminator - 1), function CUIRenditionKeySetValueForAttribute, file /BuildRoot/Library/Caches/com.apple.xbs/Sources/CoreUI/CoreUI-366.1/CoreTheme/ThemeStorage/CUIThemeRendition_Support.m, line 228.

**Comment by devcxm** [comment]
I try to extract it on macOS 10.12.1 of version 0.3.1, it works well. It seems to be use normal only on macOS 10.12 of the xcode8 compilation Asset.
[car_images_NVGAL.zip](https://github.com/devcxm/iOS-Images-Extractor/files/632729/car_images_NVGAL.zip)

**Comment by mayongl** [comment]
Thanks a lot for the help. I was using 10.11.
