### ISSUE TITLE
Assets.car 里面的 3x 图片解压不出来，使用了PDF矢量图

### ISSUE THREAD

**Issue by crespoxiao** [devcxm/iOS-Images-Extractor#12]
基本上找遍了GitHub，没有工具能把3x 图片搞出来。。。 莫非要下非常老的版本的 Xcode ？

**Comment by wonderffee** [comment]
https://blog.timac.org/2018/1112-quicklook-plugin-to-visualize-car-files/ 一文里面的Precompiled command line tool 支持导出 3x 图片

下载地址：https://blog.timac.org/2018/1112-quicklook-plugin-to-visualize-car-files/carDump.zip

源码：
https://github.com/Timac/QLCARFiles/tree/master/carDump

**Comment by devcxm** [comment]
[v0.4.0](https://github.com/devcxm/iOS-Images-Extractor/releases/tag/v0.4.0)已使用[QLCARFiles](https://github.com/Timac/QLCARFiles)替换iOS-Asset-Extractor。
