### ISSUE TITLE
图片提取不全

### ISSUE THREAD

**Issue by YongTaiSin** [devcxm/iOS-Images-Extractor#16]
好像新版xcode打包出来的assets.car文件不能全部提取出来，38M的文件提取的图片才16M

**Comment by devcxm** [comment]
[v0.4.0](https://github.com/devcxm/iOS-Images-Extractor/releases/tag/v0.4.0)已使用[QLCARFiles](https://github.com/Timac/QLCARFiles)替换[iOS-Asset-Extractor](https://github.com/Marxon13/iOS-Asset-Extractor)，理论上可以提取完整的图片资源，包括pdf文件。
