### ISSUE TITLE
xcode8打包后assets.car无法提取

### ISSUE THREAD

**Issue by Shawn-WangDapeng** [devcxm/iOS-Images-Extractor#7]
在xcode8之前 编译后提取assets.car都是正常的，今天更新了xcode8 发现无法提取，可能是苹果对assets.car的打包做了什么改变。这边能看一下 更新一下吗

**Comment by devcxm** [comment]
用v0.2.6版本https://github.com/devcxm/iOS-Images-Extractor/releases/download/v0.2.5/iOSImagesExtractor_v0.2.6.dmg可以解压，有时间我把解压的方法回退到上个版本。

**Comment by Shawn-WangDapeng** [comment]
好的 多谢回复。
