### ISSUE TITLE
Assets.car文件里的图片获取有问题

### ISSUE THREAD

**Issue by liuyuanming** [devcxm/iOS-Images-Extractor#8]
使用该工具抓取【斗鱼】，获取图片发现car_images里的图片很有问题，比如：正确的是
![success](https://cloud.githubusercontent.com/assets/11534449/19338507/1589c2b6-9150-11e6-80fe-304a690d64c5.png)

使用该工具获取到错误的是![failure](https://cloud.githubusercontent.com/assets/11534449/19338513/1bf731e2-9150-11e6-98a8-b0dc1d695405.png)
很多这样的问题

**Comment by devcxm** [comment]
之前#7反映说xcode8不能解压Assets.car，我测试好像是不行。但刚刚我重新测试一下发现又可以正常解决xcode8打包的Assets.car，我用v0.3.1版本可以提取到你截图里的图片。

**Comment by liuyuanming** [comment]
Xcode8可以解压，我用的就是。提取图片可以，但是@2x、@3x怎么变成.png

**Comment by devcxm** [comment]
用v0.3.1版本解压可以得到x2和x3的图片。我发现哪里出问题了，v0.3.1在10.11无法解压xcode8打包的Assets.car，10.12可以解压。

**Comment by liuyuanming** [comment]
你好，你没有确认我截图的问题。这是工具bug吗

**Comment by tooodooo** [comment]
10.12，v0.4.0 解压出来的图片x3的没有后缀了，按空格键预览是比x2的大，但是信息显示尺寸相同，PS里打开确实也是尺寸相同，x3等于没有

**Comment by devcxm** [comment]
项目已经恢复成v0.3.1版本了，撤销了v0.4.0版本，确认一下你们使用的是哪个版本。

**Comment by wickey-w** [comment]
Assets.car文件输出的结果是空文件夹,没有图片
